version: "3"
services:

  postgres:
    image: postgres:13.0
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: guacamole1234567890    
      POSTGRES_USER: guacamole_user
    volumes:
      - ./pginit:/docker-entrypoint-initdb.d:z  
      - ./pgdata:/var/lib/postgresql/data:z     

  guacd:
    image: guacamole/guacd:1.2.0
    restart: unless-stopped

  guacamole:
    image: guacamole/guacamole:1.2.0
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: guacamole1234567890
      POSTGRES_USER: guacamole_user
    depends_on:
      - postgres
      - guacd

  nginx:
    image: nginx:1.19.2
    restart: unless-stopped
    ports:
      - "443:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:z
